### ISSUE TITLE
wrong pluralize for 'education' >> plural = 'educations' 

### ISSUE THREAD

**Issue by danieljoppi** [dreamerslab/node.inflection#37]
$ var inflection = require('inflection')
$ inflection.pluralize('education')
'education'
$ inflection.pluralize('education') === 'educations'
false

**Comment by ben-lin** [comment]
Education can be used as both countable and uncountable noun but it's more often to be used as uncountable.

**Comment by danieljoppi** [comment]
But 'education' plural is educations in the Mongoose ... I cant configure for use countable?

**Comment by ben-lin** [comment]
The implementation is different and there is not standard. If you really don't like it you can fork it and make changes so it's 100% compatible with mongoose.
