### ISSUE TITLE
Plural, singular convertion for "woman"

### ISSUE THREAD

**Issue by bigdot** [dreamerslab/node.inflection#39]
https://github.com/dreamerslab/node.inflection/blob/master/lib/inflection.js#L350
`^(m|wom)en$` and `^(m|wom)an$` ?

right now it's `inflector.pluralize("woman") // -> womans`

**Comment by bigdot** [comment]
https://github.com/dreamerslab/node.inflection/pull/40

**Comment by ben-lin** [comment]
Thanks for the bug report and pull request. However I've fixed and published it.

**Comment by bigdot** [comment]
cool
