### ISSUE TITLE
Detect if word is singular or plural

### ISSUE THREAD

**Issue by coen-hyde** [dreamerslab/node.inflection#43]
I've come across a use case where it would be helpful to know if a word is either singular or plural. I couldn't see an immediate way to do this with the library. How could we implement this? Would this be in the scope of the library?

**Comment by ben-lin** [comment]
you can probably use a helper like this

function isPlural( str ){
  return str ===  inflection.pluralize( str ) ? true : false;
}

**Comment by coen-hyde** [comment]
Good idea. Thanks @ben-lin!

**Comment by ben-lin** [comment]
No problem :)
