### ISSUE TITLE
.underscore returns wrong values

### ISSUE THREAD

**Issue by dcrockwell** [dreamerslab/node.inflection#44]
``` javascript
inflection.underscore("Apple Tree Lake"); // "apple _tree _lake" should be "apple_tree_lake"
inflection.underscore("Apple 20 Tree Lake"); // "apple 20 _tree _lake" should be "apple_20_tree_lake"
```

**Comment by ben-lin** [comment]
In the doc it says `This function transforms String object from camelcase to underscore`. Your examples are 3 words not a camelcase string.

**Comment by dcrockwell** [comment]
Is there any other way to achieve the inflection I'm looking for with this library, or should I look into others?

**Comment by ben-lin** [comment]
Why not strip the space before calling inflection?

    var inflection = require( 'node.inflection' );
    var str = 'Apple Tree Lake';
    str = str.replace( /\s+/g, '' );
    str = inflection.underscore( str );

**Comment by dcrockwell** [comment]
Should I submit a separate bug then for when numbers are used?

``` javascript
inflection.underscore("Apple20TreeLake"); // "apple20_tree_lake" expected "apple_20_tree_lake"
```

**Comment by ben-lin** [comment]
It's not a bug. A [CamelCase](https://en.wikipedia.org/wiki/CamelCase) string is `the practice of writing compound words or phrases such that each word or abbreviation begins with a capital letter`. A number is **not** a capital letter. You can use `str.replace` to add underscore to the string like the example above.

**Comment by dcrockwell** [comment]
Fair enough, but just so you know where I'm coming from, I've a long history in the ruby language, and there they have a very solid inflector called ActiveSupport::Inflector.

In ActiveSupport::Inflector, they acknowledge several exceptions to that strict definition of CamelCase, such as: "SSLError", "Title Case With Spaces", and "Something20Including3Numbers".

**Comment by ben-lin** [comment]
Just tried with the latest release of `ActiveSupport::Inflector`.

    2.2.2 :002 > 'SSLError'.underscore
     => "ssl_error" 
    2.2.2 :003 > 'Title Case With Spaces'.underscore
     => "title case with spaces" 
    2.2.2 :004 > 'Something20Including3Numbers'.underscore
     => "something20_including3_numbers"

**Comment by dcrockwell** [comment]
I misremembered. It's been several years since I've worked with ruby. Thanks.

**Comment by ben-lin** [comment]
No problem. This supposes to be a port of the `ActiveSupport::Inflector` class but I guess it still has a few differences. However you can solve the problems with a little extra effort.
