### ISSUE TITLE
Unexpected result when using "canvas" 

### ISSUE THREAD

**Issue by Ariestattoo** [dreamerslab/node.inflection#48]
Code
`var name = 'canvas'
var pluralName = inflections.pluralize(name)
var singularName = inflections.singularize(name)
`
expect
pluralName -> canvasses 
singularName -> canvas

result 
pluralName -> canvas
singularName -> canva

**Comment by ben-lin** [comment]
It works as expected. 
```
var inflection = require('inflection');
var name = 'canvas';
var pluralName = inflection.pluralize(name);
var singularName = inflection.singularize(name);

console.log(name); // canvas
console.log(pluralName); // canvases
console.log(singularName); // canvas
```

**Comment by Ariestattoo** [comment]
My apologies ben-lin and thank you for taking the time to look into this. After digging deeper into the code (I am new to node) I was able to discover that the inflection library used was underscore.inflections. 
Thanks for your time and effort on this

**Comment by ben-lin** [comment]
No problem :)
