### ISSUE TITLE
Media turning into Medium - unrelated word

### ISSUE THREAD

**Issue by duryjames** [dreamerslab/node.inflection#52]
Hi,

We are using [http://docs.sequelizejs.com/en/latest/](http://docs.sequelizejs.com/en/latest/) which uses this library and have found that it is taking the word Media and turning it into Medium.

```
var inflection = require("inflection")
var modelName = "Media"
console.log(inflection.pluralize(modelName)) // ==> Media
console.log(inflection.singularize(modelName)) // ==> Medium
```

**Comment by ben-lin** [comment]
Hi @duryjames this is expected according to [wiktionary](https://en.wiktionary.org/wiki/media).
