### ISSUE TITLE
dasherize of camelCase word

### ISSUE THREAD

**Issue by stalniy** [dreamerslab/node.inflection#54]
Expected
```js
expect(dasherize('TestMe')).to.equal('test-me')
```

Actual
```js
expect(dasherize('TestMe')).to.equal('TestMe')
```

**Comment by stalniy** [comment]
Possible implementation:
```js
function dasherize(name) {
  return name[0].toLowerCase() + name.slice(1).replace(/[A-Z]/g, letter => `-${letter.toLowerCase()}`)
}
```

**Comment by Leestex** [comment]
@stalniy there is a hack for it:

`inflection.transform('TestMe', ['underscore', 'dasherize'])`

**Comment by ben-lin** [comment]
@stalniy I prefer @Leestex's suggestion.

**Comment by stalniy** [comment]
Then there is some inconsistency. Like why `underscore` converts camelCase to underscore but `dasherize` doesnt

**Comment by ben-lin** [comment]
Because this is a port of Rails Inflector and it was defined that way http://api.rubyonrails.org/classes/ActiveSupport/Inflector.html#method-i-dasherize

**Comment by stalniy** [comment]
That make sense. But again it's far away from being obvious or expected for those who are not familiar with rails. 

Are there any reasons to leave this as it is in rails? Or do you know why Rails team decided to support only underscored words?

**Comment by ben-lin** [comment]
I guess the original usage of this lib just for converting between model / prop name and table / field name and then the implementation stays that way.

**Comment by stalniy** [comment]
@ben-lin 
So, what is the verdict? =)
Do you plan to do something with or leave as it is?

**Comment by ben-lin** [comment]
If you send a pull request with the updated implementation, tests and docs, I'm happy to take it :)
