### ISSUE TITLE
ES6 and inflection.transform

### ISSUE THREAD

**Issue by stalniy** [dreamerslab/node.inflection#55]
Consider the next code snippet:
```js
import { transform } from 'inflection'

transform('TestMe', ['underscore', 'dasherize'])
```
**Expected result**:
test-me

**Actual result**: 
TestMe

The issue is in `transform` implementation:
This function expects `this` to be an instance of library but in provided case `this` is always a window because of ES6 destructuring
https://github.com/dreamerslab/node.inflection/blob/master/lib/inflection.js#L1068

**Comment by ben-lin** [comment]
fixed in https://github.com/dreamerslab/node.inflection/commit/faf584aafb2b3e2ac78e83ead217c6388d188615
