### ISSUE TITLE
dashcase to camelcase

### ISSUE THREAD

**Issue by tjmehta** [dreamerslab/node.inflection#62]
I noticed `camelize` does not support converting dashcase to camelcase, should it?

Example:
```js
const inflection = require('inflection')

inflection.camelize('foo-bar') // 'Foo-bar'
```

I expected the example above to return `FooBar`.

**Comment by ben-lin** [comment]
In the description it says `This function transforms String object from underscore to camelcase`

**Comment by tjmehta** [comment]
It would be nice if everything was interop. Any reason why we can't support converting everyone inflection to each other?

**Comment by ben-lin** [comment]
It was originally designed like this. Free feel to send a PR.

**Comment by tjmehta** [comment]
Nice, If you approve I am happy to send a PR. Maybe next weekend
