### ISSUE TITLE
Fish is pluralized as Fishes!

### ISSUE THREAD

**Issue by anagrath** [dreamerslab/node.inflection#69]
The plural of fish is fish!

I see fish on the list of "unaccountable" words commented out...  A little help please.

**Comment by ben-lin** [comment]
It can be both https://en.wiktionary.org/wiki/fish

**Comment by anagrath** [comment]
http://grammarist.com/usage/fish-fishes/

I am having an issue with parents complaining about this in a learning app. It says “I have 3 fishes.” The fish are all goldfish...

What do we do?

**Comment by ben-lin** [comment]
You can fork it and change it for your use case.
