### ISSUE TITLE
pluralize is not working on word Materia

### ISSUE THREAD

**Issue by etorresys** [dreamerslab/node.inflection#70]
console.log(inflection.pluralize('Materia'));
result: 'Materia'

**Comment by papb** [comment]
According to Wiktionary, [https://en.wiktionary.org/wiki/materia](https://en.wiktionary.org/wiki/materia), that word does not exist in English, so I don't see what's wrong here. Recall that `inflection` only works with English words.

**Comment by etorresys** [comment]
I understand, sorry
