### ISSUE TITLE
Would love if pluralize took an optional count argument (it would be close to the rails implementation)

### ISSUE THREAD

**Issue by benlieb** [dreamerslab/node.inflection#82]
First off, thanks for the great library! Your docs say this is based on the rails inflectors, but one that is surprisingly divergent [from the rails is pluralize](https://apidock.com/rails/ActionView/Helpers/TextHelper/pluralize).

Behold:

```ruby
pluralize(1, 'person')
# => 1 person

pluralize(2, 'person')
# => 2 people
```

I suspect you're aware of this, so I'm curious what the added benefit is?

As it stands I just wrap this in my own helper:

```javascript
export const pluralize = (count, str) => (
  count == 1 ? inflection.singularize(str) :  inflection.pluralize(str)
)
```

**Comment by nopantsmonkey** [comment]
I think node.inflection already does what you want.
[Check out this example](https://github.com/dreamerslab/node.inflection#example-code-3)

**Comment by p-kuen** [comment]
You can already do that with `inflection.inflect( str, count, [singular], [plural] ); `
