### ISSUE TITLE
Add inflect support for decimal values greater than 1 (i.e. 1.5 inches instead of 1.5 inch)

### ISSUE THREAD

**Issue by bijx** [dreamerslab/node.inflection#85]
Currently I need to use a condition before passing a value and word to the `inflection.inflect()` function that checks whether or not the value is greater than 1 since decimal values of the whole number 1 still map to singularized words. 

For example:

- `1 inch` is correct
 - `2 inches` is correct
 - `1.5 inch` is not correct

If there was a way for inflection to know that the only number to be singularized is 1 and all other numbers including decimals are pluralized, that would be great!

**Comment by p-kuen** [comment]
Fixed in #86. Thanks again.
